// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmmwcpxqmoegatfusaef.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtbXdjcHhxbW9lZ2F0ZnVzYWVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzODg4NDUsImV4cCI6MjA3MTk2NDg0NX0.qKS8yhMwNjpceOxq73Du25OJNN67h3J-hXLl32u6szY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});